name: hackathon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.7.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firestore_repository:
    path: packages/firestore_repository
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
  meta: ^1.8.0
  page_transition: ^2.0.9
  permission_handler: ^10.2.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.2
  socket_io_common: ^2.0.3
  speech_to_text: ^6.1.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.1
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/logo1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  integrations: 
    flutter_svg: true
  output: lib/gen/
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/