name: hackathon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  cloud_firestore: ^4.7.1
  equatable: ^2.0.5
  firebase_core: ^2.13.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
  meta: ^1.8.0
  table_calendar: ^3.0.9

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_gen:
  integrations: 
    flutter_svg: true
  output: lib/gen/
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/