name: hackathon_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  cross_file: ^0.3.3+4
  desktop_drop: ^0.4.1
  excel: ^2.1.0
  file_picker: ^5.3.0
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
