// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO1oVv_zBCnPrEpeKZPpK1e37BOuWbeNI',
    appId: '1:5820113346:web:9c7e6369bd3257ae95b65b',
    messagingSenderId: '5820113346',
    projectId: 'hackathon-34912',
    authDomain: 'hackathon-34912.firebaseapp.com',
    storageBucket: 'hackathon-34912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjlz83j2kycotkx96hoUP6UFLJZM7cp4k',
    appId: '1:5820113346:android:fd8a88b6c9e090a695b65b',
    messagingSenderId: '5820113346',
    projectId: 'hackathon-34912',
    storageBucket: 'hackathon-34912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKv5UxN3ZIWDq0XN3GsaJ6Bd-F5N3UFM',
    appId: '1:5820113346:ios:1ae215c7a333177c95b65b',
    messagingSenderId: '5820113346',
    projectId: 'hackathon-34912',
    storageBucket: 'hackathon-34912.appspot.com',
    iosClientId: '5820113346-fvja65m9bgbngtfa47m6cu9aba38fb8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonAdmin',
  );
}
